### ISSUE TITLE
@step-enter only firing once by default

### ISSUE THREAD

**Issue by jayden2** [shenoy/vue-scrollama#10]
`<Scrollama :debug="true" @step-enter="stepEnterHandler">
        <div v-for="index in 10" class="step" :key="'index"></div>
</Scrollama>`

stepEnterHandler only fires on first activation,  and only from direction down, even if I specifically state `once="false"`

using version 1.1.1

**Comment by jayden2** [comment]
A way around it has been to use `@step-progress`, with `progress="true"`, you get element and index, but direction returns null

**Comment by vgshenoy** [comment]
this works just fine for me, the handler fires multiple times and not just once from both directions. Do let me know if you are still facing issues, perhaps with a CodeSandbox example? Happy to help out. Closing for now.
