### ISSUE TITLE
No Components

### ISSUE THREAD

**Issue by nam-co** [shenoy/vue-scrollama#11]
Hi thanks for the script, I was wondering if its possible to use it with out components, directly on the html , for example something like <div @scrollama-step-enter="stepEnterHandler">?

Thanks for your time

**Comment by vgshenoy** [comment]
Hah, I'm sorry, for now it can be used only with a Vue component. It may be possible to think up an implementation with a Vue custom directive, but the way I see it, the component is the best implementation.
