### ISSUE TITLE
Is there a v-for example looping an array of objects?

### ISSUE THREAD

**Issue by travbus** [shenoy/vue-scrollama#7]
I can't seem to get this to work with a array of ojects **"feedPosts"** or even **feedPosts.length**  which would **equals 2**. My **{{val}}** loops and displays object fine. But I get a error
** scrollama error: no step elements.** 
It will not call handler function. **Any Ideas** Thanks
https://codesandbox.io/s/4270xl6oz0 is the snippet I was using 

**Update** So I can get a static array of objects to work. I can't get a ajax loaded arrray of objects to work
```
<Scrollama :debug="true" :offset="0.8" @step-enter="handler">
      <div
        class="step"
        v-for="(val, n) in feedPosts"
        :key="n"
        offset="0.5"
        :data-step-no="n"
      >
        step {{ n }} {{val}}
      </div>
    </Scrollama>
```
```

**Comment by vgshenoy** [comment]
Scroll interactions are setup when `<Scrollama>` is mounted, so if feedPosts is an empty array, there won't be any step elements.

The easiest way to solve this is to render `<Scrollama>` only when feedPosts is populated.

```
<Scrollama v-if="feedPosts.length" @step-enter="handler">
...
</Scrollama>
```

**Comment by travbus** [comment]
Oh man so simple this totally worked bless you !!!
