### ISSUE TITLE
Is it possible to update scrollama dynamically 

### ISSUE THREAD

**Issue by travbus** [shenoy/vue-scrollama#8]
I"m trying to use scrollama to make a dynamic infinite scoll list by tracking the index in the handler. Problem is when I update my looped array feedPosts, scrollama only works with the initial array of objects. So to get around that I  rerendered scrollama by updating :key="componentKey" to + 1 after array is updated it rerenders scrollama and new data is working with it.  Unfortunately it also resets the scroll to the top and the scrolloma flashes in the process. 

The question is it possible to update scrollama dynamically without rerender? Thanks!!

`
<Scrollama :debug="true" :offset="0.8" v-if="feedPosts.length" @step-enter="handleScroll" :once="true" class="container" :key="componentKey" >
      <template v-for="(val, feedPostsKey) in feedPosts" >
        <v-flex xs12 :key="feedPostsKey" :data-step-no="feedPostsKey" class='area noPadding noMargin'  :height="postDivHeight">

<div> some content> </div>

</v-flex>
</template>
</Scrollama>
`

**Comment by vgshenoy** [comment]
In the latest version (1.1.1), you can try calling an internal method `setup()` to re-setup scroll interactions and avoid a re-render

```
<Scrollama ref="scrollama" ...>
...
</Scrollama>
```
and once your array is updated

```
this.$refs.scrollama.setup()
```

**Comment by travbus** [comment]
It actually did work I must have had two many hoots. But I did realize I've been trying to replace an entire array with an updated one when I should push one item onto the array at a time. Thanks so much for the help. Kisses

https://codesandbox.io/s/4270xl6oz0
